version: "3.3"

services:
  backend:
    build: backend/
    image: sashumi/javabackend:test
    restart: always
    ports:
      - "9092:9092"

  frontend:
    depends_on:
      - backend
    build: frontend/
    image: sashumi/nodefrontend:test
    restart: always
    ports:
      - "3000:3000"
    links:
      - backend
